### ISSUE TITLE
checkpoint problem

### ISSUE THREAD

**Issue by ZSBSB** [huzi96/Coarse2Fine-PyTorch#14]
![image](https://user-images.githubusercontent.com/39560063/185733740-b1484956-45d1-4168-8d6a-bd574bce6be7.png)
Hello, what is the role of these three models in the training process?

**Comment by huzi96** [comment]
They are the states of the optimizers at different training stages. If the training is interrupted, you can load these optimizer states to resume training.
Check code https://github.com/huzi96/Coarse2Fine-PyTorch/blob/921fcefda8205c9790c5172777a3ec371b2a6c7e/train/train.py#L685

**Comment by ZSBSB** [comment]
OK, thanks for your answer.
