### ISSUE TITLE
How to use the model trained and some other problems? 

### ISSUE THREAD

**Issue by achel-x** [huzi96/Coarse2Fine-PyTorch#5]
After ran the `train.py`, I got some `.ckpt` file, and I want to know how load it and check its effect like the `AppEncDec.py` to compress and decomress image.  Should I write a similar one like that?

Moreover, I want to know **how to control the type of model PSNR or MS-SSIM**, and **how to control the QP values** . I am still a very freshman in this area, if my questions are too naive, please forgive it.

**Comment by achel-x** [comment]
Excuse me for bothering again. 
According to your reply,  load the `trained model` in pytorch way to use the trained model.  I tryed it recently, but I found that the reconstructed picture is incorrect. I read your code `networks.py` and `gdn_v3.py`. The `networks` in `train.py` is different from the former one, like GDN/IGDN and some other code in `class Network`. I thoght the parameters maybe change and the trained model by Pytorch is different from `.pk` model.  So load it cannot 
I still want to reconstruct the image, what can I do? should I adjust the following code `compresslow()` and `decompresslow()` to align with these changes between `train.py` and `networks .py` ?
I am not familiar with the specific code in learned image compression. I just read some papers around this topics, this is my first trial to know how it works, so please forgive me for my naive problems.

**Comment by huzi96** [comment]
Sorry for that. Indeed, if you would like to use the trained network for inference, you need some modifications. The easiest way to do this is to replace the definition of `class Net` and its related modules in the `network.py` code with the definitions in `train.py`. Besides, you need two extra functions to make it work. I would like to share the code for this but I currently do not have time to test it. If you encounter any problems please reach back to me.

        
    def encode(self, inputs):
        b, c, h, w = inputs.shape
        tb, tc, th, tw = inputs.shape

        z3 = self.a_model(inputs)
        z3_rounded = bypass_round(z3)

        z2 = self.ha_model_2(z3_rounded)
        z2_rounded = bypass_round(z2)
        
        z1 = self.ha_model_1(z2_rounded)
        z1_rounded = bypass_round(z1)
        
        h1 = self.hs_model_1(washed(z1_rounded))
        h2 = self.hs_model_2(washed(z2_rounded))

        z1_sigma = torch.abs(self.get_h1_sigma)
        z1_mu = torch.zeros_like(z1_sigma)
        
        z1_likelihoods = self.entropy_bottleneck_z1(
            z1_rounded, z1_sigma, z1_mu)

        z2_mu, z2_sigma = self.prediction_model_2(
            (b, 64*4, h//2//16, w//2//16), h1, self.sampler_2)

        z2_likelihoods = self.entropy_bottleneck_z2(
            z2_rounded, z2_sigma, z2_mu)

        z3_mu, z3_sigma = self.prediction_model_3(
            (b, 192, h//16, w//16), h2, self.sampler_3)

        z3_likelihoods = self.entropy_bottleneck_z3(
            z3_rounded, z3_sigma, z3_mu)


        test_num_pixels = inputs.size()[0] * inputs.size()[2] * inputs.size()[3]

        eval_bpp = torch.sum(torch.log(z3_likelihoods), [0,1,2,3]) / (-np.log(2) * test_num_pixels) + torch.sum(torch.log(z2_likelihoods), [0,1,2,3]) / (-np.log(2) * test_num_pixels) + torch.sum(torch.log(z1_likelihoods), [0,1,2,3]) / (-np.log(2) * test_num_pixels)

        ret = {}
        ret['z1_mu'] = z1_mu.detach().cpu().numpy()
        ret['z1_sigma'] = z1_sigma.detach().cpu().numpy()
        ret['z2_mu'] = z2_mu.detach().cpu().numpy()
        ret['z2_sigma'] = z2_sigma.detach().cpu().numpy()
        ret['z3_mu'] = z3_mu.detach().cpu().numpy()
        ret['z3_sigma'] = z3_sigma.detach().cpu().numpy()
        ret['z1_rounded'] = z1_rounded.detach().cpu().numpy()
        ret['z2_rounded'] = z2_rounded.detach().cpu().numpy()
        ret['z3_rounded'] = z3_rounded.detach().cpu().numpy()
        ret['eval_bpp'] = eval_bpp.detach().cpu().numpy()
        return ret
    
    def decode(self, inputs, stage):
        if stage == 0:
            z1_sigma = torch.abs(self.get_h1_sigma)
            z1_mu = torch.zeros_like(z1_sigma)
            
            ret = {}
            ret['z1_sigma'] = z1_sigma.detach().cpu().numpy()
            ret['z1_mu'] = z1_mu.detach().cpu().numpy()
            return ret
        
        elif stage == 1:
            z1_rounded = inputs['z1_rounded']
            h1 = self.hs_model_1(z1_rounded)
            self.h1 = h1
            z2_mu, z2_sigma = self.prediction_model_2((h1.shape[0],64*4,h1.shape[2],h1.shape[3]), h1, self.sampler_2)
            ret = {}
            ret['z2_sigma'] = z2_sigma.detach().cpu().numpy()
            ret['z2_mu'] = z2_mu.detach().cpu().numpy()
            return ret
        
        elif stage == 2:
            z2_rounded = inputs['z2_rounded']
            h2 = self.hs_model_2(z2_rounded)
            self.h2 = h2
            z3_mu, z3_sigma = self.prediction_model_3((h2.shape[0],192,h2.shape[2],h2.shape[3]), h2, self.sampler_3)
            ret = {}
            ret['z3_sigma'] = z3_sigma.detach().cpu().numpy()
            ret['z3_mu'] = z3_mu.detach().cpu().numpy()
            return ret
        
        elif stage == 3:
            z3_rounded = inputs['z3_rounded']
            pf = self.s_model(z3_rounded)
            x_tilde = self.side_recon_model(pf, self.h2, self.h1)
            x_tilde = torch.round(torch.clamp((x_tilde + 1) * 127.5, 0, 255))
            return x_tilde.detach().cpu().numpy()

**Comment by achel-x** [comment]
Thank you for your reply. I am trying to do this thing. But only change the definition of class Net() from `train.py` to `networks.py` isn't enough. Maybe I should modificate the following codes in function `compress_low()` and `decompress_low()` to adapt to these differences. Is my understanding right? 
Plus, I have another question. I found `train.py` class Network() when `mode=="test"`
`  # Bring both images back to 0..255 range.
            gt = torch.round((inputs + 1) * 127.5)
            x_hat = torch.clamp((x_tilde + 1) * 127.5, 0, 255)
            x_hat = torch.round(x_hat).float()
            v_mse = torch.mean((x_hat - gt) ** 2, [1, 2, 3])
            v_psnr = torch.mean(20 * torch.log10(255 / torch.sqrt(v_mse)), 0)
            return eval_bpp, v_psnr, x_hat, bpp1, bpp2, bpp3`

Originally, I thought the x_hat is the reconstructed image(tensor). And it show like this
![x_hat](https://user-images.githubusercontent.com/67953243/134879691-ff8f4b3e-91be-40ed-b58d-7dcfc836b9c1.PNG)
the shape of x_hat is [1, 3, 256, 256]. The train code RandomCrop the input image to 256x256 patch and preprocess make the x*2 / 255.0 -1 . What are the usages of these operations?

Through this image, I thought the x_hat is the latent representation, but it can calculate `psnr` related to original picture and reconstructed picture. That means x_hat is the decoded image, but it is actually not. I wanna know why.

**Comment by huzi96** [comment]
Does the PSNR value look good? If so, please check the following.
1. You should transpose the tensor to (256,256,3) in order to save it to an image with most of the libraries.
2. Check the pixel values before you save it as an image. Do all the values lie in [0.255]?

**Comment by achel-x** [comment]
![test0914_result](https://user-images.githubusercontent.com/67953243/134923710-6ebade8b-9c7e-478d-beba-61c9654d32a7.png)

This is my first test result. The PSNR looks ok. The x_hat in `return eval_bpp, v_psnr, x_hat, bpp1, bpp2, bpp3` is the last line of this image. It is a 0-dim tensor. After I print it, it looks like a pixel value as it in this result.

I saved the `x_tilde` as ‘x_tilde.pth` and load it separatly, then I ran the code 

![image](https://user-images.githubusercontent.com/67953243/134925770-64615f75-10a6-41f2-b072-1585737d7544.png)


The result looks great. I used `torchvision.transforms.ToPILImage` to convert the x_hat tensor to image. But the result is as the former issue looks like. So I thought it is a latent representation removed statistical redundancy, like this paper variation ... hyper prior.

https://img-blog.csdnimg.cn/20201209144447566.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzQyMjgxNDI1,size_16,color_FFFFFF,t_70

But it can calculate PSNR. I am condused.
Reading your latest reply, I try to reshape the x_hat.
Firstly, I still used the ToPILImage(), but it occured 
![image](https://user-images.githubusercontent.com/67953243/134926506-db7eb336-958a-4f86-bd5c-435815a97558.png)

Secondly, I try to convert it to numpy then to PIL image, in this way
![image](https://user-images.githubusercontent.com/67953243/134929713-25e12e87-4f8f-40ea-9888-f02611c3443a.png)

The result is alike.



This is x_hat tensor to PIL image
![x_hat_recon](https://user-images.githubusercontent.com/67953243/134930051-e6589d17-608b-4483-b044-0f8e5a326707.png)

-----------

This is the numpy to PIL image
![x_hat_recon0927](https://user-images.githubusercontent.com/67953243/134929784-92939925-59a3-4f19-8855-4347b0d55d3f.png)

**Comment by huzi96** [comment]
Comments for your second trial:
You should use transpose, not reshape.

**Comment by achel-x** [comment]
I transpose it with the shape of (256, 256, 3)
But the image is still weird.

![image](https://user-images.githubusercontent.com/67953243/135024829-322f6f92-3834-44af-98c8-e2906c39b5bf.png)
![x_hat_recon0928](https://user-images.githubusercontent.com/67953243/135024841-de9bb7e5-7126-4637-bf7b-ab86dc888aca.png)

Besides, I read the code in `trian.py` and `networks.py`

![image](https://user-images.githubusercontent.com/67953243/135025810-f34935a7-430c-456f-8ba9-546a3f2c2321.png)

![image](https://user-images.githubusercontent.com/67953243/135025954-1c8a85f8-1735-41b3-9a3e-d382d261637b.png)

As the code in `train.py` when mode==test, it onliy finish the encode part in `networks.py` not about decode. Why it can be used to calculate `v_psnr` and the value is seems good? But the x_hat can't be transformed to a normal picture.

**Comment by achel-x** [comment]
I aslo look at the gt, it looks like ok. Just a RandomCrop patch of the original picture.
![0807](https://user-images.githubusercontent.com/67953243/135028890-a09948f8-5f16-4a97-a8d4-c2bbc2de8c87.png)
![gt](https://user-images.githubusercontent.com/67953243/135028913-648f9561-b476-4900-8b01-b00c925d6f95.png)

**Comment by xisi789** [comment]
> Sorry for that. Indeed, if you would like to use the trained network for inference, you need some modifications. The easiest way to do this is to replace the definition of `class Net` and its related modules in the `network.py` code with the definitions in `train.py`. Besides, you need two extra functions to make it work. I would like to share the code for this but I currently do not have time to test it. If you encounter any problems please reach back to me.
> 
> ```
> def encode(self, inputs):
>     b, c, h, w = inputs.shape
>     tb, tc, th, tw = inputs.shape
> 
>     z3 = self.a_model(inputs)
>     z3_rounded = bypass_round(z3)
> 
>     z2 = self.ha_model_2(z3_rounded)
>     z2_rounded = bypass_round(z2)
>     
>     z1 = self.ha_model_1(z2_rounded)
>     z1_rounded = bypass_round(z1)
>     
>     h1 = self.hs_model_1(washed(z1_rounded))
>     h2 = self.hs_model_2(washed(z2_rounded))
> 
>     z1_sigma = torch.abs(self.get_h1_sigma)
>     z1_mu = torch.zeros_like(z1_sigma)
>     
>     z1_likelihoods = self.entropy_bottleneck_z1(
>         z1_rounded, z1_sigma, z1_mu)
> 
>     z2_mu, z2_sigma = self.prediction_model_2(
>         (b, 64*4, h//2//16, w//2//16), h1, self.sampler_2)
> 
>     z2_likelihoods = self.entropy_bottleneck_z2(
>         z2_rounded, z2_sigma, z2_mu)
> 
>     z3_mu, z3_sigma = self.prediction_model_3(
>         (b, 192, h//16, w//16), h2, self.sampler_3)
> 
>     z3_likelihoods = self.entropy_bottleneck_z3(
>         z3_rounded, z3_sigma, z3_mu)
> 
> 
>     test_num_pixels = inputs.size()[0] * inputs.size()[2] * inputs.size()[3]
> 
>     eval_bpp = torch.sum(torch.log(z3_likelihoods), [0,1,2,3]) / (-np.log(2) * test_num_pixels) + torch.sum(torch.log(z2_likelihoods), [0,1,2,3]) / (-np.log(2) * test_num_pixels) + torch.sum(torch.log(z1_likelihoods), [0,1,2,3]) / (-np.log(2) * test_num_pixels)
> 
>     ret = {}
>     ret['z1_mu'] = z1_mu.detach().cpu().numpy()
>     ret['z1_sigma'] = z1_sigma.detach().cpu().numpy()
>     ret['z2_mu'] = z2_mu.detach().cpu().numpy()
>     ret['z2_sigma'] = z2_sigma.detach().cpu().numpy()
>     ret['z3_mu'] = z3_mu.detach().cpu().numpy()
>     ret['z3_sigma'] = z3_sigma.detach().cpu().numpy()
>     ret['z1_rounded'] = z1_rounded.detach().cpu().numpy()
>     ret['z2_rounded'] = z2_rounded.detach().cpu().numpy()
>     ret['z3_rounded'] = z3_rounded.detach().cpu().numpy()
>     ret['eval_bpp'] = eval_bpp.detach().cpu().numpy()
>     return ret
> 
> def decode(self, inputs, stage):
>     if stage == 0:
>         z1_sigma = torch.abs(self.get_h1_sigma)
>         z1_mu = torch.zeros_like(z1_sigma)
>         
>         ret = {}
>         ret['z1_sigma'] = z1_sigma.detach().cpu().numpy()
>         ret['z1_mu'] = z1_mu.detach().cpu().numpy()
>         return ret
>     
>     elif stage == 1:
>         z1_rounded = inputs['z1_rounded']
>         h1 = self.hs_model_1(z1_rounded)
>         self.h1 = h1
>         z2_mu, z2_sigma = self.prediction_model_2((h1.shape[0],64*4,h1.shape[2],h1.shape[3]), h1, self.sampler_2)
>         ret = {}
>         ret['z2_sigma'] = z2_sigma.detach().cpu().numpy()
>         ret['z2_mu'] = z2_mu.detach().cpu().numpy()
>         return ret
>     
>     elif stage == 2:
>         z2_rounded = inputs['z2_rounded']
>         h2 = self.hs_model_2(z2_rounded)
>         self.h2 = h2
>         z3_mu, z3_sigma = self.prediction_model_3((h2.shape[0],192,h2.shape[2],h2.shape[3]), h2, self.sampler_3)
>         ret = {}
>         ret['z3_sigma'] = z3_sigma.detach().cpu().numpy()
>         ret['z3_mu'] = z3_mu.detach().cpu().numpy()
>         return ret
>     
>     elif stage == 3:
>         z3_rounded = inputs['z3_rounded']
>         pf = self.s_model(z3_rounded)
>         x_tilde = self.side_recon_model(pf, self.h2, self.h1)
>         x_tilde = torch.round(torch.clamp((x_tilde + 1) * 127.5, 0, 255))
>         return x_tilde.detach().cpu().numpy()
> ```

@huzi96 @achel-x I follow these suggestions to modify network.py. But the image is weird.

This is gt.
![10000001290](https://user-images.githubusercontent.com/41114558/139638067-813670de-72cd-4856-853e-6ad0e4c5abc6.png)

And this decode image.
![example_dec](https://user-images.githubusercontent.com/41114558/139638109-7aa819f6-e498-4407-8dc8-9994d84ca768.png)

This is code.
![image](https://user-images.githubusercontent.com/41114558/139638966-844791bc-8da6-4cee-8ae0-23bb22aa4d4e.png)
![image](https://user-images.githubusercontent.com/41114558/139639098-95660f37-7cd6-40a3-bdd0-c7b25cdf1bb7.png)
![image](https://user-images.githubusercontent.com/41114558/139639135-b96a6e4d-4805-46bf-a0c1-daf1c8b78c25.png)

**Comment by achel-x** [comment]
The modification is not located in class Net but in the load weight part. In maybe def train() or def encode() when you load the weights, you need to make a little change. Here is the part of the successful tested code provided by author. You can refer to it for your work.
'
# sd = net.state_dict()
  # td = load_tf_weights(sd, f'models/model{model_type}_qp{qp}.pk')
  # Changed to directly load the weights
  # Here we only manually load one fixed model for testing
  # You can write some code to read from command line arguments
  td = torch.load('trained_fat_l004.ckpt', map_location=torch.device(device))
  ntd = {}
  # naive way to remove 'module.' before the name of each tensor
  for k in td:
    if k[:6] == 'module':
      ntd[k[7:]] = td[k]
    else:
      ntd[k] = td[k]
  ret = net.load_state_dict(ntd, strict=False)
  print(ret)

  arr = np.array([fshape[0], fshape[1]], dtype=np.uint16)
  arr.tofile(fileobj)
  fileobj.close()
'

The comment block can't upload the .py file. So I paste the modification here.

**Comment by xisi789** [comment]
> The modification is not located in class Net but in the load weight part. In maybe def train() or def encode() when you load the weights, you need to make a little change. Here is the part of the successful tested code provided by author. You can refer to it for your work. '
> 
> # sd = net.state_dict()
> # td = load_tf_weights(sd, f'models/model{model_type}_qp{qp}.pk')
> # Changed to directly load the weights
> # Here we only manually load one fixed model for testing
> # You can write some code to read from command line arguments
> td = torch.load('trained_fat_l004.ckpt', map_location=torch.device(device)) ntd = {}
> 
> # naive way to remove 'module.' before the name of each tensor
> for k in td: if k[:6] == 'module': ntd[k[7:]] = td[k] else: ntd[k] = td[k] ret = net.load_state_dict(ntd, strict=False) print(ret)
> 
> arr = np.array([fshape[0], fshape[1]], dtype=np.uint16) arr.tofile(fileobj) fileobj.close() '
> 
> The comment block can't upload the .py file. So I paste the modification here.
@achel-x Thank you for your reply.
I loaded the self-trained model. The loading method is the same as yours. But the decoding is the same as above.
load weight part：
![image](https://user-images.githubusercontent.com/41114558/139651480-5f438694-c049-465d-90cc-8783dab6ff03.png)

In addition, where should these codes be placed?
![image](https://user-images.githubusercontent.com/41114558/139651634-a0fb9959-9398-422a-b9cd-ebd574a55bc2.png)

**Comment by achel-x** [comment]
The red bounding box is not the modification. I copy it to indicate its location in code. Just as same as the networks.py in `def compress_low()` and `def decompress_low()`. 
e.g.

def compress_low(args):
  """Compresses an image."""
  global device
  mode = 'low'
  if args.qp > 3:
    mode = 'high'
  device = torch.device(args.device)
  from PIL import Image
  # Load input image and add batch dimension.
  f = Image.open(args.input)
  fshape = [f.size[1], f.size[0], 3]
  x = np.array(f).reshape([1,] + fshape)

  compressed_file_path = args.output
  fileobj = open(compressed_file_path, mode='wb')

  qp = args.qp
  model_type = args.model_type
  print(f'model_type: {model_type}, qp: {qp}')
 

  buf = qp << 1
  buf = buf + model_type
  arr = np.array([0], dtype=np.uint8)
  arr[0] =  buf
  arr.tofile(fileobj)

  h, w = (fshape[0]//64)*64, (fshape[1]//64)*64
  if h < fshape[0]:
    h += 64
  if w < fshape[1]:
    w += 64

  pad_up = (h - fshape[0]) // 2
  pad_down = (h - fshape[0]) - pad_up
  pad_left = (w - fshape[1]) // 2
  pad_right = (w - fshape[1]) - pad_left

  x = np.pad(x, [[0, 0], [pad_up, pad_down], [pad_left, pad_right], [0, 0]])
  torch_x = (torch.tensor(x).permute(0,3,1,2).float() / 127.5) - 1
  
  if mode == 'low':
    net = NetLow().eval()
  else:
    net = NetHigh().eval()
  net = net.to(device)

  # sd = net.state_dict()
  # td = load_tf_weights(sd, f'models/model{model_type}_qp{qp}.pk')
  # Changed to directly load the weights
  # Here we only manually load one fixed model for testing
  # You can write some code to read from command line arguments
  td = torch.load('trained_fat_l004.ckpt', map_location=torch.device(device))
  ntd = {}
  # naive way to remove 'module.' before the name of each tensor
  for k in td:
    if k[:6] == 'module':
      ntd[k[7:]] = td[k]
    else:
      ntd[k] = td[k]
  ret = net.load_state_dict(ntd, strict=False)
  print(ret)

  arr = np.array([fshape[0], fshape[1]], dtype=np.uint16)
  arr.tofile(fileobj)
  fileobj.close()

**Comment by xisi789** [comment]
@achel-x Sorry to bother you again, but I did not find any difference between my code and yours. This is my code.
![image](https://user-images.githubusercontent.com/41114558/139662252-eb0b9460-748f-46ed-a265-b36aa981a4fd.png)
Could you provide the complete networks.py？
thank you very much！

**Comment by huzi96** [comment]
@xisi789 I uploaded the code for testing on a trained checkpoint. Take a look~

**Comment by xisi789** [comment]
> @xisi789 I uploaded the code for testing on a trained checkpoint. Take a look~

 Now I can get the correct output image! 
 Thank you very much！

**Comment by balabengba** [comment]
![example_dec  2 (1)](https://user-images.githubusercontent.com/49307457/141064710-5891309a-47b1-470a-99c7-7cfeb5585c0a.png)
I  test  the picture using  the code for testing on a trained checkpoint updated recently.
But the result is  not right.

**Comment by huzi96** [comment]
Check if you can correctly encode and decode images with this weight to find out what went wrong (you may want to set qp>3)
https://drive.google.com/file/d/1x2ZePCM8VaqGNWteKS55jd9LWpaPfK_O/view?usp=sharing

**Comment by balabengba** [comment]
> 检查您是否可以使用此权重正确编码和解码图像以找出问题所在（您可能需要设置 qp>3） https://drive.google.com/file/d/1x2ZePCM8VaqGNWteKS55jd9LWpaPfK_O/view?usp=sharing

Thank you very much!
I get the correct output image!

**Comment by Cdx-rgb** [comment]
> After ran the , I got some file, and I want to know how load it and check its effect like the to compress and decomress image. Should I write a similar one like that?`train.py``.ckpt``AppEncDec.py`
> 
> Moreover, I want to know **how to control the type of model PSNR or MS-SSIM**, and **how to control the QP values** . I am still a very freshman in this area, if my questions are too naive, please forgive it.

Hello!  I would like to ask if you have successfully reproduced the code. I have just learned this knowledge and do not know how to reproduce this code. What files need to be run during the entire reproduction process, and how to train this model
